//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

//#import <HBWechatHelper/UIImagePickerControllerDelegate-Protocol.h>
//#import <HBWechatHelper/UINavigationControllerDelegate-Protocol.h>

@class MMTableViewInfo, MMUIViewController, NSString;

@interface NewHBALLSettingController : UIViewController <UINavigationControllerDelegate, UIImagePickerControllerDelegate>
{
    MMTableViewInfo *manager;
    MMUIViewController *helper;
}

+ (void)initialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

